import=[
    #"~/.config/alacritty/themes/themes/tender.toml",
    "~/.config/alacritty/summer.toml",
    "~/.cache/wal/colors-alacritty.toml"
]

[colors]
transparent_background_colors=false

[font]
size=14

[font.normal]
family = 'JetBrainsMono Nerd Font'
style = 'Bold'
# family = 'FiraCode Nerd Font'
# style = 'Medium'

[font.bold]
family = 'JetBrainsMono Nerd Font'
style = 'Extrabold'
# family = 'FiraCode Nerd Font'
# style = 'Bold'

[font.italic]
# family = 'FiraCode Nerd Font'
# style = 'Normal'
family = 'JetBrainsMono Nerd Font'
style = 'Bold Italic'

[font.bold_italic]
family = 'JetBrainsMono Nerd Font'
style = 'Extrabold Italic'
# family = 'FiraCode Nerd Font'
# style = 'Bold'

[window]
decorations = "Full"
opacity = 0.7

[window.dimensions]
columns = 72
lines = 20
