import=[
    "~/.config/alacritty/themes/themes/tender.toml",
    #"~/.config/alacritty/summer.toml",
    "~/.cache/wal/colors-alacritty.toml"
]

[colors]
transparent_background_colors=true

[font.normal]
family = 'JetBrainsMono Nerd Font'
style = 'Bold'

[font.bold]
family = 'JetBrainsMono Nerd Font'
style = 'Extrabold'

[font.italic]
family = 'JetBrainsMono Nerd Font'
style = 'Bold Italic'

[font.bold_italic]
family = 'JetBrainsMono Nerd Font'
style = 'Extrabold Italic'

[window]
decorations = "Full"
opacity = 0.8

[window.dimensions]
columns = 144
lines = 40
