import=[
    #"~/.config/alacritty/themes/themes/tender.toml",
    "~/.config/alacritty/summer.toml",
    "~/.cache/wal/colors-alacritty.toml"
]

[colors]
transparent_background_colors=false

[font]
size=14

[font.normal]
family = 'JetBrainsMono Nerd Font'
style = 'Bold'

[font.bold]
family = 'JetBrainsMono Nerd Font'
style = 'Extrabold'

[font.italic]
family = 'JetBrainsMono Nerd Font'
style = 'Bold Italic'

[font.bold_italic]
family = 'JetBrainsMono Nerd Font'
style = 'Extrabold Italic'

[window]
decorations = "Full"
opacity = 0.8

[window.dimensions]
columns = 72
lines = 20
