#!/bin/env sh

args=""

while getopts 'sh' opt; do
    case "$opt" in
        s)
            args="$args -nv"
            ;;
        h|?)
            echo "Usage: $(basename "$0") [-a] [-b] [-c arg]"
            exit 1
            ;;
    esac
done

miscpkg="zsh tmux i3"

all_pkgs="$miscpkg"

for pkg in $all_pkgs; do
    stow $args "$pkg"
done

