#!/bin/env zsh

# Path configuration
export PATH="~/bin:/usr/local/bin:$PATH"
export PATH="$PATH:/usr/local/go/bin"
export PATH="$DENO_INSTALL/bin:$PATH"
export PATH="~/.bin:$PATH"
export PATH="$PATH:/home/gabrielfruet/.local/bin"
export PATH="$PATH:/home/gabrielfruet/bin/flatpak"
export PATH="$PATH:$HOME/bin"

# ZSH and Oh-My-Zsh configuration
export ZSH="$HOME/.oh-my-zsh"
export ZSH_PROFILE="/home/gabrielfruet/zsh-profile"

source $ZSH_PROFILE/sourcerer.zsh
source $HOME/pkg/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Starship prompt

# Plugins
plugins=(
  git 
  gnu-utils
  zsh-autosuggestions
  colored-man-pages
  colorize
  common-aliases
)

# Auto suggestions
bindkey '^ ' autosuggest-accept

# User configuration (Commented configurations are not active but kept for reference)
# export MANPATH="/usr/local/man:$MANPATH"
# export LANG=en_US.UTF-8
# Preferred editor settings
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# -----------WARNING-----------------
# HAS TO BE SOURCED AT THE END OF THE FILE
eval "$(starship init zsh)"
source $ZSH/oh-my-zsh.sh
