#!/bin/env zsh

set -o vi
KEYTIMEOUT=1

# Path configuration
export PATH="~/bin:/usr/local/bin:$PATH"
export PATH="$PATH:/usr/local/go/bin"
export PATH="$DENO_INSTALL/bin:$PATH"
export PATH="~/.bin:$PATH"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/bin/flatpak"
export PATH="$PATH:$HOME/bin"

# ZSH and Oh-My-Zsh configuration
export ZSH="$HOME/.oh-my-zsh"
export ZSH_PROFILE="$HOME/zsh-profile"

source $ZSH_PROFILE/sourcerer.zsh

# Starship prompt

# Plugins
plugins=(
    git 
    gnu-utils
    docker
    zsh-autosuggestions
    colored-man-pages
    colorize
    common-aliases
    alias-finder
)

# ~/.zshrc

zstyle ':omz:plugins:alias-finder' autoload yes # disabled by default
zstyle ':omz:plugins:alias-finder' longer yes # disabled by default
zstyle ':omz:plugins:alias-finder' exact yes # disabled by default
zstyle ':omz:plugins:alias-finder' cheaper yes # disabled by default

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=11'

# Auto suggestions
bindkey '^ ' autosuggest-accept

# User configuration (Commented configurations are not active but kept for reference)
# export MANPATH="/usr/local/man:$MANPATH"
# export LANG=en_US.UTF-8
# Preferred editor settings
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# -----------WARNING-----------------
# HAS TO BE SOURCED AT THE END OF THE FILE
eval "$(starship init zsh)"
eval "$(navi widget zsh)"
eval "$(opam env)"
source $ZSH/oh-my-zsh.sh
source $ZSH_CUSTOM/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source <(fzf --zsh)
if [ -f "/home/fruet/.config/fabric/fabric-bootstrap.inc" ]; then . "/home/fruet/.config/fabric/fabric-bootstrap.inc"; fi
